apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demoapp-1
spec:
  selector:
    matchLabels:
      app: springboot-demoapp-1
  template:
    metadata:
      labels:
        app: springboot-demoapp-1
    spec:
      containers:
      - name: springboot-demoapp-1
        image: kulbhushakulbhushanmayer/springboot_demoapp_1:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
